--liquibase formatted sql
--changeset kjagiello:MODELS5 failOnError:true stripComments:false splitStatements:true rollbackSplitStatements:true
--rollback drop table MODELS;
CREATE TABLE WKSP_CHARLIEDEV.MODELS(
   ID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
   FORMULA  CLOB NOT NULL,
   NAME     VARCHAR2(150)
);

COMMENT ON TABLE  WKSP_CHARLIEDEV.MODELS          IS 'Dane dot. modelu prowizyjnego';
COMMENT ON COLUMN WKSP_CHARLIEDEV.MODELS.ID       IS 'Identyfikator modelu';
COMMENT ON COLUMN WKSP_CHARLIEDEV.MODELS.FORMULA  IS 'Wzór do wyliczania prowizji';
COMMENT ON COLUMN WKSP_CHARLIEDEV.MODELS.NAME     IS 'Nazwa modelu';