--liquibase formatted sql
--changeset kjagiello:PROGRAMS5 failOnError:true stripComments:false splitStatements:true rollbackSplitStatements:true
--rollback drop table PROGRAMS;
CREATE TABLE PROGRAMS
(
   ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
   MODEL_ID        NUMBER NOT NULL,
   ORGANIZATION_ID NUMBER NOT NULL,
   DATE_FROM       DATE,
   DATE_TO         DATE
);

COMMENT ON TABLE PROGRAMS                  IS 'Dane dot. programu prowizyjnego';
COMMENT ON COLUMN PROGRAMS.ID              IS 'Identyfikator programu';
COMMENT ON COLUMN PROGRAMS.MODEL_ID        IS 'Identyfikator modelu prowizyjnego (klucz obcy)';
COMMENT ON COLUMN PROGRAMS.ORGANIZATION_ID IS 'Identyfikator organizacji sportowej (klucz obcy)';
COMMENT ON COLUMN PROGRAMS.DATE_FROM       IS 'Data rozpoczęcia';
COMMENT ON COLUMN PROGRAMS.DATE_TO         IS 'Data zakończenia';


--changeset kkazala:PROGRAM6 failOnError:true stripComments:false splitStatements:true rollbackSplitStatements:true
--comment dodanie kolumny z nazwą
--rollback ALTER TABLE WKSP_CHARLIEDEV.PROGRAMS DROP COLUMN NAME; COMMIT;
ALTER TABLE WKSP_CHARLIEDEV.PROGRAMS ADD (NAME VARCHAR2(255));
COMMENT ON COLUMN WKSP_CHARLIEDEV.PROGRAMS.DATE_TO IS 'Nazwa programu';

--changeset kkazala:PROGRAM7 failOnError:true stripComments:false splitStatements:true rollbackSplitStatements:true
--comment dodanie kolumny z datą ostatniego uruchomienia programu
--rollback ALTER TABLE WKSP_CHARLIEDEV.PROGRAMS DROP COLUMN LAST_START; COMMIT;
ALTER TABLE WKSP_CHARLIEDEV.PROGRAMS ADD (LAST_START VARCHAR2(255));
COMMENT ON COLUMN WKSP_CHARLIEDEV.PROGRAMS.LAST_START IS 'Data ostatniego uruchomienia programu';