--liquibase formatted sql
--changeset kkazala:SESSIONS_SPEC_PKG failOnError:true stripComments:false splitStatements:true rollbackSplitStatements:true runOnChange:true context:pakiety
--comment dodanie spec pakietu do rozliczania sesji
--rollback select 1 from dual;
CREATE OR REPLACE PACKAGE SESSIONS_BODY_PKG AS

  PROCEDURE CALCULATE_SALES_COMMISSIONS (
    in_program_id IN NUMBER
    );

  PROCEDURE INSERT_CALCULATED_SALES_COMMISSIONS (
    in_program_name WKSP_CHARLIEDEV.CALCULATED_SALES_COMMISSIONS.PROGRAM_NAME%TYPE,
    in_model_name WKSP_CHARLIEDEV.CALCULATED_SALES_COMMISSIONS.MODEL_NAME%TYPE,
    in_calculated_amount WKSP_CHARLIEDEV.CALCULATED_SALES_COMMISSIONS.CALCULATED_AMOUNT%TYPE,
    in_date_to WKSP_CHARLIEDEV.CALCULATED_SALES_COMMISSIONS.DATE_TO%TYPE,
    in_date_from WKSP_CHARLIEDEV.CALCULATED_SALES_COMMISSIONS.DATE_FROM%TYPE,
    in_calculation_date WKSP_CHARLIEDEV.CALCULATED_SALES_COMMISSIONS.CALCULATION_DATE%TYPE,
    in_sport_league WKSP_CHARLIEDEV.SPORTS_LEAGUES.NAME%TYPE
  );

END SESSIONS_BODY_PKG;