--liquibase formatted sql
--changeset kkazala:COMMISSION_DATA_V failOnError:true stripComments:false splitStatements:true rollbackSplitStatements:true runOnChange:true
--rollback drop view WKSP_CHARLIEDEV.COMMISSION_DATA_V;
CREATE OR REPLACE VIEW WKSP_CHARLIEDEV.COMMISSION_DATA_V AS
SELECT
  BV.BET_AMOUNT,
  BV.BET_MULTIPLIER,
  BV.BET_TYPE,
  BV.PROMOTION_NAME,
  BV.PROMOTION_MULTIPLIER,
  BV.SPORTS_LEAGUE_ID,
  BV.BET_DATE,
  PR.DATE_FROM,
  PR.DATE_TO,
  MD.FORMULA,
  SL.MODIFIER AS SPORTS_MODIFIER
FROM BETS_V BV
JOIN PROGRAMS PR ON (PR.ORGANIZATION_ID = BV.SPORTS_LEAGUE_ID)
JOIN MODELS MD ON (MD.ID = PR.MODEL_ID)
JOIN SPORTS_LEAGUES SL ON PR.ORGANIZATION_ID = SL.ID;

COMMENT ON MATERIALIZED VIEW WKSP_CHARLIEDEV.COMMISSION_DATA_V IS 'Źródło danych do obliczania prowizji.';